name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup build cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Download Cryptominisat
        run: |
          echo "PWD=${PWD}"
          echo "GITHUB_WORKSPACE=${GITHUB_WORKSPACE}"
          mkdir -p bin
          wget -O bin/cryptominisat5 https://github.com/msoos/cryptominisat/releases/download/5.6.8/cryptominisat5-linux-amd64-gauss
          chmod +x bin/cryptominisat5
          echo "::add-path::$(realpath bin)"

      - name: Build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
